# Generated by Django 2.2 on 2020-08-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(db_column='official_email', on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
    ]
