# Generated by Django 2.2 on 2020-08-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200830_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarypackage',
            old_name='net_monthly_salary',
            new_name='gross_monthly_salary',
        ),
        migrations.RenameField(
            model_name='salarypackage',
            old_name='net_yearly_salary',
            new_name='gross_yearly_salary',
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(db_column='official_email', on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
    ]
