# Generated by Django 2.2 on 2020-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200830_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebonus',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='promotion_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary_issued_date',
            field=models.DateField(),
        ),
    ]
