# Generated by Django 2.2 on 2020-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200830_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='promotion_date',
            field=models.DateField(blank=True),
        ),
    ]
