# Generated by Django 2.2 on 2020-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200830_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypackage',
            name='bonus',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
