# Generated by Django 2.2 on 2020-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_salarypackage_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('current_year', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
