# Generated by Django 2.2 on 2020-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_financialyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypackage',
            name='salary_this_year',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
