# Generated by Django 2.2 on 2020-08-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_salarypackage_salary_this_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypackage',
            name='total_salary_income',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
