# Generated by Django 2.2 on 2020-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_payroll_salary_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='_house_rent_as_per_salary',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='_house_rent_band',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='_house_rent_basic_pay_50',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='house_rent_exempt',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
