# Generated by Django 2.2 on 2020-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20200831_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='_house_rent_as_per_salary',
            new_name='house_rent_as_per_salary',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='_house_rent_band',
            new_name='house_rent_band',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='_house_rent_basic_pay_50',
            new_name='house_rent_basic_pay_50',
        ),
    ]
