# Generated by Django 2.2 on 2020-08-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20200831_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.FloatField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.FinancialYear')),
            ],
            options={
                'verbose_name': 'Investment Credit',
            },
        ),
        migrations.CreateModel(
            name='InvestmentRebateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.FloatField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.FinancialYear')),
            ],
            options={
                'verbose_name': 'Tax Rebate Rule',
                'verbose_name_plural': 'Tax Rebate Rules',
            },
        ),
        migrations.DeleteModel(
            name='TaxRebateRule',
        ),
        migrations.AddField(
            model_name='payroll',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.FinancialYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='investment_credit',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='investment_rebate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
