# Generated by Django 2.2 on 2020-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20200831_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentrebaterule',
            options={'verbose_name': 'Investment Rebate Rule',
                     'verbose_name_plural': 'Investment Rebate Rules'},
        ),
        migrations.RenameField(
            model_name='financialyear',
            old_name='financial_year',
            new_name='financial_year_end',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='financial_year',
        ),
        migrations.AddField(
            model_name='financialyear',
            name='financial_year_start',
            field=models.DateField(auto_now_add=True, default="2020-07-01"),
            preserve_default=False,
        ),
    ]
