# Generated by Django 2.2 on 2020-09-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20200901_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('yearly_investment_amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.FinancialYear')),
            ],
            options={
                'verbose_name': 'Employee Investment',
                'verbose_name_plural': 'Employee Investments',
            },
        ),
    ]
