# Generated by Django 2.2 on 2020-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employeeinvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='salary_this_month',
            new_name='salary_this_month_without_investment',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='tax_this_month',
            new_name='tax_this_month_without_investment',
        ),
    ]
