# Generated by Django 2.2 on 2020-09-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20200901_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='mobile',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='providend_fund',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='conveyance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='house_rent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='medical',
            field=models.FloatField(),
        ),
    ]
