# Generated by Django 2.2 on 2020-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20200902_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='basic',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
