# Generated by Django 2.2 on 2020-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_payroll_basic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='monthly_taxable_income',
            new_name='gross_salary_this_month',
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_salary_this_month',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
