# Generated by Django 2.2 on 2020-10-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20200902_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='salary_package',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='conveyance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='house_rent',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='medical',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mobile',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='providend_fund',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
