# Generated by Django 2.2 on 2020-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20201001_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gratuity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_monthly_salary',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='house_rent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_bill',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_bill',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='providend_fund',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='last_increment_date',
            field=models.DateField(blank=True, default="2020-07-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinvestment',
            name='yearly_investment_amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
