# Generated by Django 2.2 on 2020-10-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20201001_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
