# Generated by Django 2.2 on 2020-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20201002_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gross_monthly_salary',
            field=models.FloatField(),
        ),
    ]
