# Generated by Django 2.2 on 2020-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20201002_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gratuity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='providend_fund',
            field=models.FloatField(default=0.0),
        ),
    ]
