# Generated by Django 2.2 on 2021-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_auto_20210116_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='monthly_incentive',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='special_allowence_7',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='monthly_incentive',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='special_allowence_7',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='tax_paid_this_year',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
