# Generated by Django 2.2 on 2021-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_auto_20210327_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarypackage',
            old_name='tax_paid_this_year',
            new_name='tax_paid_this_year_with_rebate',
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='tax_paid_this_year_without_investment',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
