# Generated by Django 2.2 on 2021-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_auto_20210328_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='advance_tax_paid_last_financial_year',
            field=models.FloatField(default=0.0),
        ),
    ]
