# Generated by Django 2.2 on 2021-03-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_employee_advance_tax_paid_last_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxAdvencePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('advance_tax_paid_last_financial_year', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
