# Generated by Django 2.2 on 2021-03-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_employeetaxadvencepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='advance_tax_paid_last_financial_year',
        ),
    ]
