# Generated by Django 2.2 on 2021-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_auto_20210330_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='performance_bonus',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='performance_bonus_given',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
