# Generated by Django 2.2 on 2021-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_auto_20210331_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='financial_year',
            field=models.DateField(default=None),
        ),
    ]
