# Generated by Django 2.2 on 2021-03-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_payroll_financial_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypackage',
            name='tax_paid_this_year_with_rebate',
        ),
        migrations.RemoveField(
            model_name='salarypackage',
            name='tax_paid_this_year_without_investment',
        ),
    ]
