# Generated by Django 2.2 on 2021-01-15 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('077d6a4b-550e-470d-9c77-d665cb417022'), editable=False, primary_key=True, serialize=False),
        ),
    ]
