# Generated by Django 2.2 on 2021-01-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210116_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=301959223915162924937222346034163193941, editable=False, primary_key=True, serialize=False),
        ),
    ]
