# Generated by Django 2.2 on 2021-01-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deduction_attr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='earning_attr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
